stages:
  split:
    cmd: python src/data/data_split.py
    deps:
      - src/data/data_split.py
      - data/raw/raw.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize:
    cmd: python src/data/normalize.py
    deps:
      - src/data/normalize.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - data/normalized/X_train.csv
      - data/normalized/X_test.csv
      - data/normalized/y_train.csv
      - data/normalized/y_test.csv

  train:
    cmd: python src/models/training.py
    deps:
      - src/models/training.py
      - data/normalized/X_train.csv
      - data/normalized/X_test.csv
      - data/normalized/y_train.csv
      - data/normalized/y_test.csv
    outs:
      - models/model.joblib
